/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tiffany_phippy_JniHello */

#ifndef _Included_com_tiffany_phippy_JniHello
#define _Included_com_tiffany_phippy_JniHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tiffany_phippy_JniHello
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tiffany_phippy_JniHello_SayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
